#!/usr/bin/env bash
set -euo pipefail

# ┌─────────────────────────────────────────────────────────────────────────────┐
# │ AWS Infrastructure Setup — GABAG Operations Platform
# │ Auto-generated by Forge. Run once after cloning.
# │
# │ Prerequisites:
# │   - AWS CLI configured (aws configure)
# │   - Terraform >= 1.0 installed
# │   - Bun installed
# │
# │ Usage:
# │   bash scripts/aws-setup.sh
# │
# │ This script will:
# │   1. Generate secrets and write .env (gitignored)
# │   2. Run terraform for shared → dev → prod
# │   3. Update .env with real RDS endpoint
# │   4. Run prisma migrate + seed
# └─────────────────────────────────────────────────────────────────────────────┘

REGION="eu-west-1"
PROJECT="gabag-operations-platform"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  AWS Setup — GABAG Operations Platform"
echo "║  Region: $REGION"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# ── Step 1: Verify AWS credentials ──────────────────────────────────────────
echo "► Step 1/10: Verifying AWS credentials…"
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text 2>/dev/null) || {
  echo "  ✗ AWS CLI not configured. Run: aws configure"; exit 1;
}
echo "  ✓ AWS Account: $ACCOUNT_ID"

# Derive canonical names — account ID guarantees global S3 uniqueness
STATE_BUCKET="$PROJECT-tf-state-$ACCOUNT_ID"
LOCKS_TABLE="$PROJECT-terraform-locks"

# ── Step 2: Bootstrap Terraform state backend ────────────────────────────────
echo ""
echo "► Step 2/10: Bootstrapping Terraform state backend…"

# Create S3 state bucket (idempotent)
if aws s3api head-bucket --bucket "$STATE_BUCKET" 2>/dev/null; then
  echo "  ✓ State bucket already exists: $STATE_BUCKET"
else
  aws s3api create-bucket     --bucket "$STATE_BUCKET"     --region "$REGION"     --create-bucket-configuration LocationConstraint="$REGION" > /dev/null
  aws s3api put-bucket-versioning     --bucket "$STATE_BUCKET"     --versioning-configuration Status=Enabled
  echo "  ✓ State bucket created: $STATE_BUCKET"
fi

# Create DynamoDB locks table (idempotent)
if aws dynamodb describe-table --table-name "$LOCKS_TABLE" --region "$REGION" > /dev/null 2>&1; then
  echo "  ✓ Locks table already exists: $LOCKS_TABLE"
else
  aws dynamodb create-table     --table-name "$LOCKS_TABLE"     --attribute-definitions AttributeName=LockID,AttributeType=S     --key-schema AttributeName=LockID,KeyType=HASH     --billing-mode PAY_PER_REQUEST     --region "$REGION" > /dev/null
  echo "  ✓ Locks table created: $LOCKS_TABLE"
fi

# Patch backend.tf files to use the canonical bucket/table names.
# Q holds a double-quote; avoids " escaping issues inside template literals.
Q='"'
for BACKEND_FILE in terraform/envs/shared/backend.tf terraform/envs/dev/backend.tf terraform/envs/prod/backend.tf; do
  if [ -f "$BACKEND_FILE" ]; then
    sed -i.bak       -e "s|bucket[[:space:]]*=.*|bucket         = $Q$STATE_BUCKET$Q|"       -e "s|dynamodb_table[[:space:]]*=.*|dynamodb_table = $Q$LOCKS_TABLE$Q|"       "$BACKEND_FILE"
    rm -f "$BACKEND_FILE.bak"
  fi
done
echo "  ✓ backend.tf files patched"

# ── Step 3: Generate secrets ─────────────────────────────────────────────────
echo ""
echo "► Step 3/10: Generating secrets…"

if [ -f .env ]; then
  echo "  .env already exists — skipping secret generation"
  echo "  (Delete .env and .tf-secrets to regenerate)"
else
  AUTH_SECRET=$(openssl rand -base64 32)
  CRON_SECRET=$(openssl rand -base64 32)
  DB_PASSWORD=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 24)
  AWS_KEY_ID=$(aws configure get aws_access_key_id 2>/dev/null || echo "")
  AWS_SECRET=$(aws configure get aws_secret_access_key 2>/dev/null || echo "")

  # Write .tf-secrets (sourced by terraform steps — never committed)
  cat > .tf-secrets << SECEOF
DB_PASSWORD=$DB_PASSWORD
AUTH_SECRET=$AUTH_SECRET
CRON_SECRET=$CRON_SECRET
S3_ACCESS_KEY_ID=$AWS_KEY_ID
S3_SECRET_ACCESS_KEY=$AWS_SECRET
SECEOF

  # Write .env for the app
  cat > .env << ENVEOF
# Auto-generated by aws-setup.sh — DO NOT COMMIT
DATABASE_URL=postgresql://postgres:$DB_PASSWORD@PENDING_RDS_ENDPOINT/gabag_operations_platform_dev?sslmode=no-verify
DIRECT_URL=postgresql://postgres:$DB_PASSWORD@PENDING_RDS_ENDPOINT/gabag_operations_platform_dev?sslmode=no-verify
AUTH_SECRET=$AUTH_SECRET
NEXTAUTH_SECRET=$AUTH_SECRET
AUTH_TRUST_HOST=true
NEXTAUTH_URL=http://localhost:3000
NEXT_PUBLIC_APP_URL=http://localhost:3000
S3_ACCESS_KEY_ID=$AWS_KEY_ID
S3_SECRET_ACCESS_KEY=$AWS_SECRET
S3_REGION=eu-west-1
S3_BUCKET_NAME=
S3_PUBLIC_URL=
AWS_REGION=eu-west-1
CRON_SECRET=$CRON_SECRET
SEED_ADMIN_EMAIL=admin@example.com
SEED_ADMIN_PASSWORD=changeme123
ENVEOF

  echo "  ✓ .env created with generated secrets"
  echo "  ✓ DB_PASSWORD: $DB_PASSWORD"
  echo "  ✓ AUTH_SECRET: (generated)"
fi

# Source secrets for terraform — simple key=value, works on macOS + Linux
if [ ! -f .tf-secrets ]; then
  echo "  ✗ .tf-secrets not found. Delete .env and re-run this script."
  exit 1
fi
set -a
source .tf-secrets
set +a

export TF_VAR_db_password="$DB_PASSWORD"
export TF_VAR_auth_secret="$AUTH_SECRET"
export TF_VAR_cron_secret="$CRON_SECRET"
export TF_VAR_s3_access_key_id="$S3_ACCESS_KEY_ID"
export TF_VAR_s3_secret_access_key="$S3_SECRET_ACCESS_KEY"

# ── Step 3: Terraform shared (VPC + RDS) ─────────────────────────────────────
echo ""
echo "► Step 4/10: Terraform shared (VPC + RDS) — this takes 5-10 minutes…"
cd terraform/envs/shared
terraform init -input=false
terraform apply -auto-approve -input=false
DB_ENDPOINT=$(terraform output -raw db_endpoint 2>/dev/null || echo "PENDING")
cd "$REPO_ROOT"

# ── Step 4: Update .env + create app databases ───────────────────────────────
echo ""
echo "► Step 5/10: Updating .env with RDS endpoint + creating app databases…"
if [ "$DB_ENDPOINT" != "PENDING" ]; then
  sed -i.bak "s|PENDING_RDS_ENDPOINT|$DB_ENDPOINT|g" .env
  rm -f .env.bak
  echo "  ✓ .env updated: $DB_ENDPOINT"

  # Create gabag_dev and gabag_prod databases (idempotent — skips if they exist)
  if command -v psql &>/dev/null; then
    export PGPASSWORD="$DB_PASSWORD"
    for DB_NAME in "gabag_operations_platform_dev" "gabag_operations_platform_prod"; do
      psql "postgresql://postgres:$DB_PASSWORD@$DB_ENDPOINT:5432/postgres?sslmode=require"         -c "CREATE DATABASE \"$DB_NAME\";" 2>/dev/null         && echo "  ✓ Database created: $DB_NAME"         || echo "  ✓ Database already exists: $DB_NAME"
    done
    unset PGPASSWORD
  else
    echo "  ⚠ psql not found — databases will be created by Prisma migrate"
    echo "    Install psql: brew install libpq && brew link --force libpq"
  fi
else
  echo "  ⚠ Could not get RDS endpoint — update .env manually"
fi

# ── Step 5: Create GitHub Actions IAM user ───────────────────────────────────
echo ""
echo "► Step 6/10: Creating GitHub Actions IAM user…"
aws iam create-user --user-name github-actions-user 2>/dev/null && echo "  ✓ IAM user created: github-actions-user" || echo "  ✓ IAM user already exists: github-actions-user"

# ── Step 6: Terraform dev ────────────────────────────────────────────────────
echo ""
echo "► Step 7/10: Terraform dev (S3 + Amplify + EventBridge + IAM)…"
cd terraform/envs/dev
terraform init -input=false
terraform apply -auto-approve -input=false
DEV_BUCKET=$(terraform output -raw s3_bucket_name 2>/dev/null || echo "")
cd "$REPO_ROOT"

if [ -n "$DEV_BUCKET" ]; then
  sed -i.bak "s|^S3_BUCKET_NAME=.*|S3_BUCKET_NAME=$DEV_BUCKET|" .env
  rm -f .env.bak
fi

# ── Step 7: Terraform prod ───────────────────────────────────────────────────
echo ""
echo "► Step 8/10: Terraform prod…"
cd terraform/envs/prod
terraform init -input=false
terraform apply -auto-approve -input=false
cd "$REPO_ROOT"

# ── Step 8: Commit Terraform lock files + clean up secrets ───────────────────
echo ""
echo "► Step 9/10: Committing Terraform lock files and cleaning up…"
find . -name ".amplify-branch-env" -type d -exec rm -rf {} + 2>/dev/null || true
find . -name "*.tfplan" -delete 2>/dev/null || true
echo "  ✓ Secret files removed"

# Commit .terraform.lock.hcl files so CI uses the same provider versions.
# These are generated by terraform init above and are now tracked (not gitignored).
LOCK_FILES=$(find terraform/envs -name ".terraform.lock.hcl" 2>/dev/null)
if [ -n "$LOCK_FILES" ]; then
  git add terraform/envs/shared/.terraform.lock.hcl          terraform/envs/dev/.terraform.lock.hcl          terraform/envs/prod/.terraform.lock.hcl 2>/dev/null || true
  git diff --cached --quiet ||     git commit -m "chore: pin Terraform provider versions (lock files)"
  echo "  ✓ Terraform lock files committed"
else
  echo "  ⚠ No .terraform.lock.hcl files found — run terraform init in each env"
fi

# ── Step 9: Prisma migrate + seed ────────────────────────────────────────────
echo ""
echo "► Step 10/10: Database setup (Prisma migrate + seed)…"
bun install --frozen-lockfile 2>/dev/null || bun install
bun run db:generate
bun run db:migrate || echo "  ⚠ Migration skipped (run manually if DB not reachable)"
bun run db:seed || echo "  ⚠ Seed skipped"

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  ✓ Setup complete!"
echo "║"
echo "║  Next steps:"
echo "║  1. Connect Amplify to GitHub in AWS Console"
echo "║     https://eu-west-1.console.aws.amazon.com/amplify/home?region=eu-west-1"
echo "║  2. Set Amplify env vars (copy from .env)"
echo "║  3. Push to dev branch to trigger first deploy"
echo "║     git checkout -b dev && git push origin dev"
echo "║"
echo "║  GitHub Actions secrets (Settings → Secrets → Actions):"
echo "║  See docs/GITHUB_SECRETS.md for the list"
echo "╚══════════════════════════════════════════════════════════════╝"
